// Optimized mockup images (generated by scripts/prepare-mockup-images.mjs).
export const IMAGES = {
  homeHero: "/images/heroes/home-hero.jpg",
  waterHero: "/images/heroes/water-hero.jpg",
  sustainHero: "/images/heroes/sustain-hero.jpg",
  waterCta: "/images/textures/water-cta.jpg",
  waterCard: "/images/cards/water-theme.jpg",
  sustainCard: "/images/cards/sustain-theme.jpg",
  adrCard: "/images/cards/adr-theme.jpg",
  flowScreen1: "/images/screens/flow-dashboard-1.jpg",
  flowScreen2: "/images/screens/flow-dashboard-2.jpg",
} as const;
