// Optimized mockup images (generated by scripts/prepare-mockup-images.mjs).
export const IMAGES = {
  homeHero: "/images/heroes/home-hero.jpg",
  waterHero: "/images/heroes/water-hero.jpg",
  sustainHero: "/images/heroes/sustain-forest.svg",
  sustainHeroPhoto: "/images/heroes/sustain-hero.jpg",
  sustainCta: "/images/textures/sustain-cta.jpg",
  waterCta: "/images/textures/water-cta.jpg",
  waterCard: "/images/cards/water-theme.jpg",
  sustainCard: "/images/cards/sustain-theme.jpg",
  energyCard: "/images/cards/energy-theme.svg",
  adrCard: "/images/cards/adr-theme.jpg",
  flowScreen1: "/images/screens/flow-dashboard-1.jpg",
  flowScreen2: "/images/screens/flow-dashboard-2.jpg",
} as const;
